#! /usr/bin/env bash

set -e

SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_DIR=$(cd $SCRIPTS_DIR/.. && pwd)
VENV_DIR=$(echo $PROJECT_DIR/.venv)

cd $PROJECT_DIR

if [ ! -d $VENV_DIR ]; then
  virtualenv -p python3.6 $VENV_DIR
fi

. $VENV_DIR/bin/activate
pip install pip-tools
pip-compile -o requirements.txt requirements.in
pip install -r requirements.txt
pip install ipython

