#! /usr/bin/env bash

set -e

SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_DIR=$(cd $SCRIPTS_DIR/.. && pwd)
VENV_DIR=$(echo $PROJECT_DIR/.venv)

cd $PROJECT_DIR

if [ ! -d $VENV_DIR ]; then
  virtualenv -p python3.6 $VENV_DIR
fi

. $VENV_DIR/bin/activate
pip install pip-tools

# order matters in the REQ_FILES list because files depend on each other
REQ_FILES=(requirements requirements-test)
for fName in ${REQ_FILES[*]}; do
  pip-compile -o ${fName}.txt ${fName}.in
  pip install -r ${fName}.txt
done

