#! /usr/bin/env bash

set -e

SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_DIR=$(cd $SCRIPTS_DIR/.. && pwd)
VENV_DIR=$(echo $PROJECT_DIR/.venv)
LIB_DIR=$(echo $PROJECT_DIR/lib)

if [ ! -f '/usr/bin/llvm-config-11' ]; then
  sudo apt-get install -y llvm-11 clang
fi

cd $PROJECT_DIR

if [ ! -d $VENV_DIR ]; then
  virtualenv -p python3.11 $VENV_DIR
fi

. $VENV_DIR/bin/activate
pip install pip-tools

# order matters in the REQ_FILES list because files depend on each other
REQ_FILES=(requirements requirements-test)
for fName in ${REQ_FILES[*]}; do
  pip-compile -o ${fName}.txt ${fName}.in
  pip install -r ${fName}.txt
done

# download the antlr jar file
if [ ! -d $LIB_DIR ]; then 
  mkdir $LIB_DIR
fi
if [ ! -f $LIB_DIR/antlr-4.13.0-complete.jar ]; then
  pushd $LIB_DIR
  wget https://www.antlr.org/download/antlr-4.13.0-complete.jar
  popd
fi

# install LLVM
# wget https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz
# ... other LLVM install steps
