#! /usr/bin/env bash

set -e

SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_DIR=$(cd $SCRIPTS_DIR/.. && pwd)
VENV_DIR=$(echo $PROJECT_DIR/.venv)
SRC_DIR=$(echo $PROJECT_DIR/src)
EXAMPLE_DIR=$(echo $PROJECT_DIR/example)

cd $PROJECT_DIR

if [ ! -d $VENV_DIR ]; then
  tput setaf 1
  echo "No virtualenv directory: .venv"
  tput sgr0
  exit 1
fi

. $VENV_DIR/bin/activate

# delete the temp directory that will be created later
declare -a TMP_DIR_ARRAY
function cleanup_tmp_dirs {
  for tmpDir in "${TMP_DIR_ARRAY[@]}"; do
    if [ -d $tmpDir ]; then
      rm -fr $tmpDir
    fi
  done
}
trap cleanup_tmp_dirs EXIT

cd $EXAMPLE_DIR
DIR_LIST=$(ls)

for dName in $DIR_LIST; do
  cd ${EXAMPLE_DIR}/$dName

  mkdir -p ./ll


  TMP_LLVM_DIR=$(mktemp -d)
  TMP_DIR_ARRAY+=( $TMP_LLVM_DIR )

  python3 $SRC_DIR/main.py $PWD/src > ${TMP_LLVM_DIR}/main.ll
  # cat ${TMP_LLVM_DIR}/main.ll


  echo "Testing: ${dName}" 
  diff ${TMP_LLVM_DIR}/main.ll ./ll/main.ll
  # git add ./ll/main.ll
done
