#! /usr/bin/env bash

set -e

SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_DIR=$(cd $SCRIPTS_DIR/.. && pwd)
VENV_DIR=$(echo $PROJECT_DIR/.venv)
SRC_DIR=$(echo $PROJECT_DIR/src)
BIN_DIR='./bin'
APP_NAME=${1:-$(basename $PWD)}


if [ ! -d $VENV_DIR ]; then
  tput setaf 1
  echo "No virtualenv directory: .venv"
  tput sgr0
  exit 1
fi

. $VENV_DIR/bin/activate

if [ ! -d $BIN_DIR ]; then
  mkdir -p $BIN_DIR
fi

TMP_LLVM_DIR=$(mktemp -d)
# echo "TEMP DIR:  $TMP_LLVM_DIR"
function cleanup {
  rm -fr ${TMP_LLVM_DIR}
}
trap cleanup EXIT

python3 $SRC_DIR/main.py $PWD/src > ${TMP_LLVM_DIR}/main.ll
# cat ${TMP_LLVM_DIR}/main.ll

$SCRIPTS_DIR/build-llvm.sh $TMP_LLVM_DIR main
mv $TMP_LLVM_DIR/main $BIN_DIR/$APP_NAME
