#! /usr/bin/env bash

set -e

SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_DIR=$(cd $SCRIPTS_DIR/.. && pwd)
VENV_DIR=$(echo $PROJECT_DIR/.venv)
SRC_DIR=$(echo $PROJECT_DIR/src)
BIN_DIR='./bin'
APP_NAME=$(basename $PWD)


if [ ! -d $VENV_DIR ]; then
  echo "No virtualenv directory: .venv"
  exit 1
fi

. $VENV_DIR/bin/activate

if [ ! -d $BIN_DIR ]; then
  mkdir -p $BIN_DIR
fi

TMP_LLVM_IR=$(mktemp)
function cleanup {
  rm -f ${TMP_LLVM_IR}.*
}
trap cleanup EXIT

python $SRC_DIR/main.py $PWD/src > ${TMP_LLVM_IR}.ll

$SCRIPTS_DIR/build-llvm.sh $TMP_LLVM_IR
mv $TMP_LLVM_IR $BIN_DIR/$APP_NAME

